05-16 09:34:48 jdbc[55]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:181)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:315)
	at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:341)
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:226)
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:199)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:66)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:34:48 jdbc[55]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:34:48 jdbc[55]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:181)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:315)
	at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:341)
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:226)
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:199)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:66)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:34:48 jdbc[55]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:34:48 jdbc[55]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:34:48 jdbc[55]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:181)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:315)
	at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:341)
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:226)
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:199)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:66)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:34:48 jdbc[55]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:181)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:315)
	at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:341)
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:226)
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:199)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:66)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:34:48 jdbc[55]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:34:48 jdbc[55]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:34:49 jdbc[55]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:181)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:315)
	at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:341)
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:226)
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:199)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:66)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:34:54 jdbc[108]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:34:54 jdbc[108]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:181)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:315)
	at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:341)
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:226)
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:199)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:66)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:34:54 jdbc[108]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:34:55 jdbc[108]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:181)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:315)
	at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:341)
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:226)
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:199)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:66)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:34:55 jdbc[108]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:181)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:315)
	at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:341)
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:226)
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:199)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:66)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:34:55 jdbc[108]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:34:55 jdbc[108]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:181)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:315)
	at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:341)
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:226)
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:199)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:66)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:34:55 jdbc[108]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:34:55 jdbc[108]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:181)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:315)
	at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:341)
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:226)
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:199)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:66)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:34:55 jdbc[108]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:34:55 jdbc[108]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:34:55 jdbc[108]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:34:55 jdbc[108]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:34:55 jdbc[108]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:34:55 jdbc[108]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:181)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:315)
	at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:341)
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:226)
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:199)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:66)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:34:55 jdbc[108]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:34:55 jdbc[108]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:34:56 jdbc[108]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:181)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:315)
	at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:341)
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:226)
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:199)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:66)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:34:56 jdbc[108]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:34:56 jdbc[108]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:34:56 jdbc[108]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:181)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:315)
	at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:341)
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:226)
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:199)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:66)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:34:56 jdbc[108]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:181)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:315)
	at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:341)
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:226)
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:199)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:66)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:34:57 jdbc[108]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:181)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:315)
	at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:341)
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:226)
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:199)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:66)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:34:57 jdbc[108]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:35:02 jdbc[159]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:181)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:315)
	at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:341)
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:226)
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:199)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:66)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:35:02 jdbc[159]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:35:02 jdbc[159]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:35:02 jdbc[159]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:181)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:315)
	at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:341)
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:226)
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:199)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:66)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:35:02 jdbc[159]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:35:02 jdbc[159]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:35:02 jdbc[159]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:35:02 jdbc[159]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:181)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:315)
	at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:341)
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:226)
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:199)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:66)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:35:02 jdbc[159]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:35:02 jdbc[159]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:181)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:315)
	at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:341)
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:226)
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:199)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:66)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:35:02 jdbc[159]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:35:02 jdbc[159]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:181)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:315)
	at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:341)
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:226)
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:199)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:66)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:35:02 jdbc[159]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:35:02 jdbc[159]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:35:02 jdbc[159]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:181)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:315)
	at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:341)
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:226)
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:199)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:66)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:35:02 jdbc[159]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:35:03 jdbc[159]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:181)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:315)
	at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:341)
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:226)
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:199)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:66)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:35:03 jdbc[159]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:35:03 jdbc[159]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:35:03 jdbc[159]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:181)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:315)
	at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:341)
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:226)
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:199)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:66)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:35:03 jdbc[159]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:35:03 jdbc[159]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:181)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:315)
	at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:341)
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:226)
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:199)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:66)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:35:03 jdbc[159]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:181)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:315)
	at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:341)
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:226)
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:199)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:66)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:35:03 jdbc[159]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:35:03 jdbc[159]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:35:03 jdbc[159]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:181)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:315)
	at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:341)
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:226)
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:199)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:66)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:35:03 jdbc[159]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
05-16 09:35:04 jdbc[159]: java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:99)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:121)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:181)
	at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:315)
	at org.h2.jdbcx.JdbcDataSource.getPooledConnection(JdbcDataSource.java:341)
	at org.h2.jdbcx.JdbcConnectionPool.getConnectionNow(JdbcConnectionPool.java:226)
	at org.h2.jdbcx.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:199)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:66)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)

org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.get(DbException.java:135)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:175)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:120)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:93)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.cyb.app.h2.H2ServerManager.crudTest(H2ServerManager.java:65)
	at com.cyb.app.h2.H2ServerManager.h2Test(H2ServerManager.java:91)
	at com.cyb.app.h2.H2ServerManager.main(H2ServerManager.java:96)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-171]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	... 12 more
